service: auth-server

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  timeout: 6

functions:
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
